services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - webnet

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - webnet
    environment:
      - DATABASE_URL=postgresql://postgres:GRACEGRACE2020@e@db:5432/postgres

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: GRACEGRACE2020@e
      POSTGRES_DB: postgres

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - webnet
      
  proxy:
    image: jc21/nginx-proxy-manager:latest
    ports:
      - "8090:81"
      - "80:80"
      - "443:443"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    depends_on:
      - db

networks:
  webnet:

volumes:
  postgres_data:
